// Code generated by MockGen. DO NOT EDIT.
// Source: cellar/pkg/settings (interfaces: IConfiguration)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_configuration.go -package=mocks cellar/pkg/settings IConfiguration
//

// Package mocks is a generated GoMock package.
package mocks

import (
	settings "cellar/pkg/settings"
	cryptography "cellar/pkg/settings/cryptography"
	datastore "cellar/pkg/settings/datastore"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIConfiguration is a mock of IConfiguration interface.
type MockIConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockIConfigurationMockRecorder
	isgomock struct{}
}

// MockIConfigurationMockRecorder is the mock recorder for MockIConfiguration.
type MockIConfigurationMockRecorder struct {
	mock *MockIConfiguration
}

// NewMockIConfiguration creates a new mock instance.
func NewMockIConfiguration(ctrl *gomock.Controller) *MockIConfiguration {
	mock := &MockIConfiguration{ctrl: ctrl}
	mock.recorder = &MockIConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConfiguration) EXPECT() *MockIConfigurationMockRecorder {
	return m.recorder
}

// App mocks base method.
func (m *MockIConfiguration) App() settings.IAppConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "App")
	ret0, _ := ret[0].(settings.IAppConfiguration)
	return ret0
}

// App indicates an expected call of App.
func (mr *MockIConfigurationMockRecorder) App() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "App", reflect.TypeOf((*MockIConfiguration)(nil).App))
}

// Datastore mocks base method.
func (m *MockIConfiguration) Datastore() datastore.IDatastoreConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Datastore")
	ret0, _ := ret[0].(datastore.IDatastoreConfiguration)
	return ret0
}

// Datastore indicates an expected call of Datastore.
func (mr *MockIConfigurationMockRecorder) Datastore() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Datastore", reflect.TypeOf((*MockIConfiguration)(nil).Datastore))
}

// Encryption mocks base method.
func (m *MockIConfiguration) Encryption() cryptography.IEncryptionConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Encryption")
	ret0, _ := ret[0].(cryptography.IEncryptionConfiguration)
	return ret0
}

// Encryption indicates an expected call of Encryption.
func (mr *MockIConfigurationMockRecorder) Encryption() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Encryption", reflect.TypeOf((*MockIConfiguration)(nil).Encryption))
}

// Logging mocks base method.
func (m *MockIConfiguration) Logging() settings.ILoggingConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Logging")
	ret0, _ := ret[0].(settings.ILoggingConfiguration)
	return ret0
}

// Logging indicates an expected call of Logging.
func (mr *MockIConfigurationMockRecorder) Logging() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Logging", reflect.TypeOf((*MockIConfiguration)(nil).Logging))
}

// RateLimit mocks base method.
func (m *MockIConfiguration) RateLimit() settings.IRateLimitConfiguration {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RateLimit")
	ret0, _ := ret[0].(settings.IRateLimitConfiguration)
	return ret0
}

// RateLimit indicates an expected call of RateLimit.
func (mr *MockIConfigurationMockRecorder) RateLimit() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RateLimit", reflect.TypeOf((*MockIConfiguration)(nil).RateLimit))
}
