// Code generated by MockGen. DO NOT EDIT.
// Source: cellar/pkg/settings (interfaces: IAppConfiguration)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_app_configuration.go -package=mocks cellar/pkg/settings IAppConfiguration
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIAppConfiguration is a mock of IAppConfiguration interface.
type MockIAppConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockIAppConfigurationMockRecorder
	isgomock struct{}
}

// MockIAppConfigurationMockRecorder is the mock recorder for MockIAppConfiguration.
type MockIAppConfigurationMockRecorder struct {
	mock *MockIAppConfiguration
}

// NewMockIAppConfiguration creates a new mock instance.
func NewMockIAppConfiguration(ctrl *gomock.Controller) *MockIAppConfiguration {
	mock := &MockIAppConfiguration{ctrl: ctrl}
	mock.recorder = &MockIAppConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIAppConfiguration) EXPECT() *MockIAppConfigurationMockRecorder {
	return m.recorder
}

// BindAddress mocks base method.
func (m *MockIAppConfiguration) BindAddress() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BindAddress")
	ret0, _ := ret[0].(string)
	return ret0
}

// BindAddress indicates an expected call of BindAddress.
func (mr *MockIAppConfigurationMockRecorder) BindAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BindAddress", reflect.TypeOf((*MockIAppConfiguration)(nil).BindAddress))
}

// ClientAddress mocks base method.
func (m *MockIAppConfiguration) ClientAddress() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClientAddress")
	ret0, _ := ret[0].(string)
	return ret0
}

// ClientAddress indicates an expected call of ClientAddress.
func (mr *MockIAppConfigurationMockRecorder) ClientAddress() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClientAddress", reflect.TypeOf((*MockIAppConfiguration)(nil).ClientAddress))
}

// MaxAccessCount mocks base method.
func (m *MockIAppConfiguration) MaxAccessCount() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxAccessCount")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxAccessCount indicates an expected call of MaxAccessCount.
func (mr *MockIAppConfigurationMockRecorder) MaxAccessCount() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxAccessCount", reflect.TypeOf((*MockIAppConfiguration)(nil).MaxAccessCount))
}

// MaxExpirationSeconds mocks base method.
func (m *MockIAppConfiguration) MaxExpirationSeconds() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxExpirationSeconds")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxExpirationSeconds indicates an expected call of MaxExpirationSeconds.
func (mr *MockIAppConfigurationMockRecorder) MaxExpirationSeconds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxExpirationSeconds", reflect.TypeOf((*MockIAppConfiguration)(nil).MaxExpirationSeconds))
}

// MaxFileSizeMB mocks base method.
func (m *MockIAppConfiguration) MaxFileSizeMB() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MaxFileSizeMB")
	ret0, _ := ret[0].(int)
	return ret0
}

// MaxFileSizeMB indicates an expected call of MaxFileSizeMB.
func (mr *MockIAppConfigurationMockRecorder) MaxFileSizeMB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MaxFileSizeMB", reflect.TypeOf((*MockIAppConfiguration)(nil).MaxFileSizeMB))
}

// Version mocks base method.
func (m *MockIAppConfiguration) Version() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Version")
	ret0, _ := ret[0].(string)
	return ret0
}

// Version indicates an expected call of Version.
func (mr *MockIAppConfigurationMockRecorder) Version() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Version", reflect.TypeOf((*MockIAppConfiguration)(nil).Version))
}
