// Code generated by MockGen. DO NOT EDIT.
// Source: cellar/pkg/settings (interfaces: IRateLimitConfiguration)
//
// Generated by this command:
//
//	mockgen -destination=../mocks/mock_ratelimit_configuration.go -package=mocks cellar/pkg/settings IRateLimitConfiguration
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIRateLimitConfiguration is a mock of IRateLimitConfiguration interface.
type MockIRateLimitConfiguration struct {
	ctrl     *gomock.Controller
	recorder *MockIRateLimitConfigurationMockRecorder
	isgomock struct{}
}

// MockIRateLimitConfigurationMockRecorder is the mock recorder for MockIRateLimitConfiguration.
type MockIRateLimitConfigurationMockRecorder struct {
	mock *MockIRateLimitConfiguration
}

// NewMockIRateLimitConfiguration creates a new mock instance.
func NewMockIRateLimitConfiguration(ctrl *gomock.Controller) *MockIRateLimitConfiguration {
	mock := &MockIRateLimitConfiguration{ctrl: ctrl}
	mock.recorder = &MockIRateLimitConfigurationMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIRateLimitConfiguration) EXPECT() *MockIRateLimitConfigurationMockRecorder {
	return m.recorder
}

// Enabled mocks base method.
func (m *MockIRateLimitConfiguration) Enabled() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enabled")
	ret0, _ := ret[0].(bool)
	return ret0
}

// Enabled indicates an expected call of Enabled.
func (mr *MockIRateLimitConfigurationMockRecorder) Enabled() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enabled", reflect.TypeOf((*MockIRateLimitConfiguration)(nil).Enabled))
}

// HealthCheckRequestsPerWindow mocks base method.
func (m *MockIRateLimitConfiguration) HealthCheckRequestsPerWindow() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HealthCheckRequestsPerWindow")
	ret0, _ := ret[0].(int)
	return ret0
}

// HealthCheckRequestsPerWindow indicates an expected call of HealthCheckRequestsPerWindow.
func (mr *MockIRateLimitConfigurationMockRecorder) HealthCheckRequestsPerWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HealthCheckRequestsPerWindow", reflect.TypeOf((*MockIRateLimitConfiguration)(nil).HealthCheckRequestsPerWindow))
}

// Tier1RequestsPerWindow mocks base method.
func (m *MockIRateLimitConfiguration) Tier1RequestsPerWindow() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tier1RequestsPerWindow")
	ret0, _ := ret[0].(int)
	return ret0
}

// Tier1RequestsPerWindow indicates an expected call of Tier1RequestsPerWindow.
func (mr *MockIRateLimitConfigurationMockRecorder) Tier1RequestsPerWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tier1RequestsPerWindow", reflect.TypeOf((*MockIRateLimitConfiguration)(nil).Tier1RequestsPerWindow))
}

// Tier2RequestsPerWindow mocks base method.
func (m *MockIRateLimitConfiguration) Tier2RequestsPerWindow() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tier2RequestsPerWindow")
	ret0, _ := ret[0].(int)
	return ret0
}

// Tier2RequestsPerWindow indicates an expected call of Tier2RequestsPerWindow.
func (mr *MockIRateLimitConfigurationMockRecorder) Tier2RequestsPerWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tier2RequestsPerWindow", reflect.TypeOf((*MockIRateLimitConfiguration)(nil).Tier2RequestsPerWindow))
}

// Tier3RequestsPerWindow mocks base method.
func (m *MockIRateLimitConfiguration) Tier3RequestsPerWindow() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Tier3RequestsPerWindow")
	ret0, _ := ret[0].(int)
	return ret0
}

// Tier3RequestsPerWindow indicates an expected call of Tier3RequestsPerWindow.
func (mr *MockIRateLimitConfigurationMockRecorder) Tier3RequestsPerWindow() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Tier3RequestsPerWindow", reflect.TypeOf((*MockIRateLimitConfiguration)(nil).Tier3RequestsPerWindow))
}

// WindowSeconds mocks base method.
func (m *MockIRateLimitConfiguration) WindowSeconds() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WindowSeconds")
	ret0, _ := ret[0].(int)
	return ret0
}

// WindowSeconds indicates an expected call of WindowSeconds.
func (mr *MockIRateLimitConfigurationMockRecorder) WindowSeconds() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WindowSeconds", reflect.TypeOf((*MockIRateLimitConfiguration)(nil).WindowSeconds))
}
