basePath: /v2
definitions:
  httputil.HTTPError:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: status bad request
        type: string
    type: object
  models.SecretContentResponse:
    properties:
      content:
        example: my very secret text
        type: string
      id:
        example: 22b6fff1be15d1fd54b7b8ec6ad22e80e66275195c914c4b0f9652248a498680
        type: string
    type: object
  models.SecretMetadataResponseV2:
    properties:
      access_count:
        example: 1
        type: integer
      access_limit:
        example: 10
        type: integer
      content_type:
        example: text
        type: string
      expiration:
        example: 1970-01-01 00:00:00 UTC
        type: string
      id:
        example: 22b6fff1be15d1fd54b7b8ec6ad22e80e66275195c914c4b0f9652248a498680
        type: string
    type: object
info:
  contact:
    email: dev@ariavesta.com
    name: Aria Vesta
    url: http://cellar-app.io
  description: Simple secret sharing with the infrastructure you already trust
  license:
    name: MIT
    url: https://gitlab.com/cellar-app/cellar-api/-/blob/main/LICENSE.txt
  title: Cellar
paths:
  /v2/secrets:
    post:
      consumes:
      - multipart/form-data
      parameters:
      - description: Secret content
        in: formData
        name: content
        type: string
      - description: Access limit
        in: formData
        name: access_limit
        type: integer
      - description: Expiration of the secret in Unix Epoch Time
        in: formData
        name: expiration_epoch
        required: true
        type: integer
      - description: Secret content as a file
        in: formData
        name: file
        type: file
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.SecretMetadataResponseV2'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Create Secret
  /v2/secrets/{id}:
    delete:
      consumes:
      - application/json
      parameters:
      - description: Secret ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: ""
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Delete Secret
    get:
      consumes:
      - application/json
      parameters:
      - description: Secret ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SecretMetadataResponseV2'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Get Secret Metadata
  /v2/secrets/{id}/access:
    post:
      consumes:
      - application/json
      parameters:
      - description: Secret ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      - application/octet-stream
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.SecretContentResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/httputil.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/httputil.HTTPError'
      summary: Access Secret Content. If the content is a file it the response will
        be an application/octet-stream
swagger: "2.0"
